version=2.3+26.1

# release, beta & alpha
versionType=release
group=com.lukasabbe.bookshelfinspector
java_version=25

# Common
minecraft_version=26.1.2
mod_name=BookshelfInspector
mod_author=Lukasabbe
mod_id=bookshelfinspector
license=MIT
credits=
description=Inspect any book in a chiseled bookshelf.
minecraft_version_range=[26.1, 26.2)

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric https://fabricmc.net/develop/
fabric_version=0.150.0+26.1.2
fabric_loader_version=0.19.2

# NeoForge
neoforge_version=26.1.2.68-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Global dep
YAML_snake=2.5
cloth_config=26.1.154
mod_menu=18.0.0-alpha.8