license = "MIT"

modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "lukasabbe"
description = "Inspect any book in a chiseled bookshelf."

logoFile = "../assets/bookshelfinspector/icon.png"
#displayURL = "..."
#issueTrackerUrl = "..."

[[mixins]]
config = "bookshelfinspector.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"